[build]
  Command = "NODE_ENV=staging yarn build:netlify"
  Functions = "lambda"
  Publish = "build"
[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "https://logs1414.xiti.com"
